# Generated by Django 5.0.3 on 2024-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=150)),
                ('Glycemic_Index', models.IntegerField(max_length=4)),
                ('Calories', models.IntegerField(max_length=3)),
                ('Carbohydrates', models.IntegerField(max_length=5)),
                ('Protein', models.IntegerField(max_length=3)),
                ('Fat', models.IntegerField(max_length=3)),
                ('Suitable_for_Diabetes', models.IntegerField(max_length=3)),
                ('Suitable_for_Blood_Pressure', models.IntegerField(max_length=3)),
                ('Sodium_Content', models.IntegerField(max_length=3)),
                ('Potassium_Content', models.IntegerField(max_length=5)),
                ('Magnesium_Content', models.IntegerField(max_length=4)),
                ('Calcium_Content', models.IntegerField(max_length=4)),
                ('Fiber_Content', models.IntegerField(max_length=3)),
            ],
        ),
    ]
