# Generated by Django 5.0.3 on 2024-03-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
