# Generated by Django 5.0.3 on 2024-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0002_rename_foods_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Calcium_Content',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='Calories',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Carbohydrates',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fat',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fiber_Content',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Glycemic_Index',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='Magnesium_Content',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='Potassium_Content',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='Protein',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Sodium_Content',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Suitable_for_Blood_Pressure',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='Suitable_for_Diabetes',
            field=models.FloatField(max_length=3),
        ),
    ]
